import { test, expect } from "@playwright/test"

test("guest shopping, cookie isolation, quantity, checkout handoff and removal", async ({ page, context, browser }) => {
  await page.goto("/products")
  await expect(page.getByRole("heading", { name: "テスト缶バッジ" })).toBeVisible()
  await page.getByRole("link", { name: "次の商品を見る" }).click()
  await expect(page).toHaveURL(/after=page2/)
  await page.getByRole("link", { name: /テスト缶バッジ/ }).click()
  await expect(page.getByRole("option", { name: "B（売り切れ）" })).toBeDisabled()
  await page.getByLabel("数量").fill("2")
  await page.getByRole("button", { name: "カートに追加" }).click()
  await expect(page.getByRole("status")).toHaveText("カートを更新しました。")
  const cookie = (await context.cookies()).find(cookie => cookie.name === "candy_rain_shopify_cart")!
  expect(cookie.httpOnly).toBe(true)
  expect(cookie.sameSite).toBe("Lax")
  expect(cookie.secure).toBe(true)
  expect(await page.content()).not.toContain("TEST_CART_SECRET")
  await page.getByRole("link", { name: "カートを見る" }).click()
  await expect(page.getByLabel("数量")).toHaveValue("2")
  await page.reload()
  await expect(page.getByLabel("数量")).toHaveValue("2")
  await page.getByLabel("数量").fill("3")
  await page.getByRole("button", { name: "更新", exact: true }).click()
  await expect(page.getByRole("status")).toHaveText("カートを更新しました。")
  await expect(page.getByText("￥1,500", { exact: true })).toBeVisible()
  expect(await page.content()).not.toContain("TEST_CART_SECRET")
  const other = await browser.newContext()
  const otherPage = await other.newPage()
  await otherPage.goto("http://127.0.0.1:3107/cart")
  await expect(otherPage.getByText(/カートの中は空です/)).toBeVisible()
  await other.close()
  await page.route("https://candy-rain-test.myshopify.com/cart/**", route => route.fulfill({ contentType: "text/html", body: "<h1>Checkout handoff</h1>" }))
  await page.getByRole("button", { name: "購入手続きへ" }).click()
  await expect(page).toHaveURL("https://candy-rain-test.myshopify.com/cart/c/test-checkout")
  await page.goto("/cart")
  await page.getByRole("button", { name: "削除" }).click()
  await expect(page.getByText(/カートの中は空です/)).toBeVisible()
})

test("empty, failure, unknown product, accounts and mobile navigation", async ({ page }) => {
  await page.goto("/products?after=empty")
  await expect(page.getByText("商品はただいま準備中です")).toBeVisible()
  await page.goto("/products?after=error")
  await expect(page.getByRole("alert").filter({ hasText: "ストアに接続できません" })).toBeVisible()
  expect(await page.content()).not.toContain("upstream secret")
  await page.goto("/products/nonexistent")
  await expect(page.getByText("404")).toBeVisible()
  await page.goto("/orders")
  await expect(page.getByRole("link", { name: "アカウント画面へ" })).toHaveAttribute("href", "https://candy-rain-test.myshopify.com/account")
  await page.goto("/signin")
  await expect(page).toHaveURL(/\/account$/)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/products/badge")
  await expect(page.getByRole("button", { name: "カートに追加" })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole("button", { name: "メニューを開く" }).click()
  await expect(page.getByRole("navigation", { name: "モバイルナビゲーション" })).toBeVisible()
})

test("stock rejection, adjustment warning and expired cart recovery", async ({ page, context }) => {
  await context.addCookies([{ name: "candy_rain_shopify_cart", value: "gid://shopify/Cart/expired?key=expired", url: "http://127.0.0.1:3107", httpOnly: true }])
  await page.goto("/products/badge")
  await page.getByLabel("数量").fill("13")
  await page.getByRole("button", { name: "カートに追加" }).click()
  await expect(page.getByRole("alert").filter({ hasText: "カートを更新できませんでした" })).toBeVisible()
  await page.getByLabel("数量").fill("14")
  await page.getByRole("button", { name: "カートに追加" }).click()
  await expect(page.getByRole("status")).toContainText("カートが調整されました")
  await page.goto("/cart")
  await expect(page.getByLabel("数量")).toHaveValue("3")
})

test("商品画像をクリックとキーボードで切り替え、購入するバリエーションを維持する", async ({ page }) => {
  await page.goto("/products/badge")
  const gallery = page.getByRole("region", { name: "商品画像" })
  const mainImage = gallery.getByRole("img")
  await expect(mainImage).toHaveAttribute("alt", "テスト缶バッジ A")
  const soldOutImage = gallery.getByRole("button", { name: "テスト缶バッジ Bの画像を表示" })
  await soldOutImage.click()
  await expect(mainImage).toHaveAttribute("alt", "テスト缶バッジ B")
  await expect(mainImage).toHaveAttribute("src", /variant-2/)
  await expect(soldOutImage).toHaveAttribute("aria-pressed", "true")
  await expect(page.getByLabel("バリエーション")).toHaveValue("gid://shopify/ProductVariant/1")
  const cover = gallery.getByRole("button", { name: "テスト缶バッジ 全体の画像を表示" })
  await cover.focus()
  await page.keyboard.press("Enter")
  await expect(mainImage).toHaveAttribute("alt", "テスト缶バッジ 全体")
  await expect(soldOutImage).toHaveAttribute("aria-pressed", "false")
  await page.getByLabel("バリエーション").selectOption("gid://shopify/ProductVariant/3")
  await expect(mainImage).toHaveAttribute("alt", "テスト缶バッジ C")
  await expect(gallery.getByRole("button", { name: "テスト缶バッジ Cの画像を表示" })).toHaveAttribute("aria-pressed", "true")
  await page.setViewportSize({ width: 390, height: 844 })
  const first = gallery.getByRole("button", { name: "テスト缶バッジ Aの画像を表示" })
  await first.focus()
  await page.keyboard.press("Space")
  await expect(mainImage).toHaveAttribute("alt", "テスト缶バッジ A")
  await expect(mainImage).toHaveJSProperty("complete", true)
  expect(await mainImage.evaluate((image: HTMLImageElement) => image.naturalWidth)).toBeGreaterThan(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})


test("バリエーションに紐づかない商品画像も表示できる", async ({ page }) => {
  await page.goto("/products/badge")
  const gallery = page.getByRole("region", { name: "商品画像" })
  await expect(gallery.getByRole("button", { name: "テスト缶バッジ 全体の画像を表示" })).toHaveCount(1)
  await gallery.getByRole("button", { name: "テスト缶バッジ 裏面の画像を表示" }).click()
  await expect(gallery.getByRole("img")).toHaveAttribute("alt", "テスト缶バッジ 裏面")
  await expect(gallery.getByRole("img")).toHaveAttribute("src", /variant-4/)
  await expect(page.getByLabel("バリエーション")).toHaveValue("gid://shopify/ProductVariant/1")
})
